### ISSUE TITLE
Bug in running posterior-analysis.sh

### ISSUE THREAD

**Issue by biozhangzhou** [birc-aeh/coalhmm#8]
Hi  Mailund:
This is the bug I met in running posterior-analysis.sh;it seems the sum of each row of EM was not equal to 2; What should I do to avoid it ?
![image](https://user-images.githubusercontent.com/42492970/184544168-09fdbf87-6f29-4566-a520-ee684de1a5fa.png)
EM
![image](https://user-images.githubusercontent.com/42492970/184544204-5d3358c0-4dcb-4fa1-abaf-f76e7cacf623.png)

**Comment by mailund** [comment]
I'm not sure what is happening here. The first error is an indentation issue in the Python code, but I don't see a problem in the repository code. The second is a key error, but if the file that marginal-posterior.py reads is corrupted (because the previous step failed), that is to be expected.

The EM data you show doesn't sum to one (or two; it can also do that) for each row, but I don't see how you get it if the script doesn't run?

**Comment by biozhangzhou** [comment]
Thank you for your reply.
Actually I added one line "print EM" before "assert all(allclose(row.sum(), 2.0) for row in Em)"  so that I can see what EM really is.
Also I can successfully run this test script without any warning after comment out four lines as shown below. Is it ok to skip these codes?
![image](https://user-images.githubusercontent.com/42492970/184656800-14c9be7f-ccaf-4468-9382-7bc615b65b3c.png)

**Comment by mailund** [comment]
The assertions do not modify the data in any way, so they are safe to skip in that particular sense. If they should fail, and don't, then, of course, there is the risk that you get incorrect results.

**Comment by biozhangzhou** [comment]
Thank you anyway.
